import { format, subDays, subMonths, startOfMonth, endOfMonth, differenceInCalendarDays } from "date-fns";
import { FieldPath } from "firebase-admin/firestore";
import { adminDb } from "@/lib/firebase-admin";
import { getSubAdminManagedUserIds, getUserRoles } from "@/lib/permissions";
import type { UserProfile, Invoice, Commission } from "@/types";
import type {
  AdminReportActivityRow,
  AdminReportAuditRow,
  AdminReportCommissionRow,
  AdminReportInvoiceRow,
  AdminReportSummary,
  AdminReportType,
} from "@/lib/admin-reports-types";
import {
  isInReportRange,
  pctChange,
  pickInvoiceDateMs,
  pickReportDateMs,
  reportEndOfDay,
  reportStartOfDay,
  reportToMs,
  uidFromFirestorePath,
} from "@/lib/admin-reports-utils";
import { getAffiliateAuditTrail } from "@/lib/affiliate-audit-trail-server";
import { getAffiliateAuditEventLabel } from "@/lib/affiliate-audit-trail-display";

export type BuildAdminReportInput = {
  from: Date;
  to: Date;
  allTime?: boolean;
  clientId?: string;
  reportType?: AdminReportType;
  callerUid: string;
};

async function loadAllUsers(): Promise<UserProfile[]> {
  const snap = await adminDb().collection("users").get();
  return snap.docs.map((d) => ({ ...(d.data() as UserProfile), uid: d.id }));
}

function resolveClientScope(
  users: UserProfile[],
  callerUid: string,
  clientId?: string
): { clientUsers: UserProfile[]; scopeLabel: string } {
  const caller = users.find((u) => u.uid === callerUid);
  const managedIds = getSubAdminManagedUserIds(caller, users);

  let clients = users.filter((u) => {
    if (!u.uid || u.uid === callerUid) return false;
    const roles = getUserRoles(u);
    if (roles.includes("admin") || roles.includes("sub_admin")) return false;
    if (roles.includes("commission_agent") && !roles.includes("user")) return false;
    return true;
  });

  if (managedIds !== null) {
    clients = clients.filter((u) => u.uid && managedIds.includes(u.uid));
  }

  if (clientId) {
    const one = clients.find((u) => u.uid === clientId);
    return {
      clientUsers: one ? [one] : [],
      scopeLabel: one?.name || one?.email || clientId,
    };
  }

  return { clientUsers: clients, scopeLabel: "All clients" };
}

async function loadInvoicesForUsers(userIds: string[]): Promise<AdminReportInvoiceRow[]> {
  const rows: AdminReportInvoiceRow[] = [];
  const batches = await Promise.all(
    userIds.map(async (userId) => {
      const snap = await adminDb().collection(`users/${userId}/invoices`).get();
      return snap.docs.map((doc) => ({ userId, id: doc.id, data: doc.data() as Invoice }));
    })
  );

  for (const batch of batches) {
    for (const { userId, id, data } of batch) {
      const dateMs = pickInvoiceDateMs(data as Record<string, unknown>);
      rows.push({
        id,
        userId,
        clientName: data.soldTo?.name || "",
        clientEmail: data.soldTo?.email || "",
        invoiceNumber: data.invoiceNumber || id,
        date: data.date || "",
        status: data.status || "pending",
        subtotal: data.subtotal || 0,
        grandTotal: data.grandTotal || 0,
        autoGenerated: data.autoGenerated,
        createdAt: dateMs ? new Date(dateMs).toISOString() : "",
      });
    }
  }
  return rows;
}

async function loadCommissions(): Promise<AdminReportCommissionRow[]> {
  const snap = await adminDb().collection("commissions").get();
  return snap.docs.map((doc) => {
    const data = doc.data() as Commission;
    return {
      id: doc.id,
      agentId: data.agentId,
      agentName: data.agentName,
      clientId: data.clientId,
      clientName: data.clientName,
      invoiceNumber: data.invoiceNumber,
      invoiceAmount: data.invoiceAmount || 0,
      commissionAmount: data.commissionAmount || 0,
      commissionRate: data.commissionRate,
      tier: data.tier,
      status: data.status,
      createdAt: new Date(reportToMs(data.createdAt) || Date.now()).toISOString(),
      paidAt: data.paidAt ? new Date(reportToMs(data.paidAt)).toISOString() : undefined,
    };
  });
}

async function loadCollectionGroupActivities(
  collectionName: string,
  allowedUserIds: Set<string>,
  from: Date,
  to: Date,
  allTime: boolean,
  mapRow: (path: string, data: FirebaseFirestore.DocumentData) => AdminReportActivityRow | null
): Promise<AdminReportActivityRow[]> {
  const rows: AdminReportActivityRow[] = [];
  let lastDoc: FirebaseFirestore.QueryDocumentSnapshot | undefined;
  const pageSize = 1000;

  while (true) {
    let query = adminDb()
      .collectionGroup(collectionName)
      .orderBy(FieldPath.documentId())
      .limit(pageSize);
    if (lastDoc) query = query.startAfter(lastDoc);

    const snap = await query.get();
    if (snap.empty) break;

    for (const doc of snap.docs) {
      const uid = uidFromFirestorePath(doc.ref.path);
      if (!allowedUserIds.has(uid)) continue;
      const row = mapRow(doc.ref.path, doc.data());
      if (!row) continue;
      const d = new Date(reportToMs(row.occurredAt));
      if (!isInReportRange(d, from, to, allTime)) continue;
      rows.push(row);
    }

    lastDoc = snap.docs[snap.docs.length - 1];
    if (snap.size < pageSize) break;
  }

  return rows;
}

async function loadAuditRows(
  clientUsers: UserProfile[],
  from: Date,
  to: Date,
  allTime: boolean
): Promise<AdminReportAuditRow[]> {
  const rows: AdminReportAuditRow[] = [];

  const affiliateEvents = await getAffiliateAuditTrail({ limit: 500 });
  for (const event of affiliateEvents) {
    const d = new Date(event.occurredAt);
    if (!isInReportRange(d, from, to, allTime)) continue;
    rows.push({
      id: event.id,
      module: "Affiliate",
      eventType: getAffiliateAuditEventLabel(event.type),
      description: event.description || event.action || "",
      agentName: event.agentName || undefined,
      performedBy: event.performedByName || event.performedByUid || undefined,
      occurredAt: event.occurredAt,
    });
  }

  const sampleClients = clientUsers.slice(0, 25);
  for (const client of sampleClients) {
    if (!client.uid) continue;
    const snap = await adminDb()
      .collection(`users/${client.uid}/auditTrail`)
      .orderBy("occurredAt", "desc")
      .limit(50)
      .get()
      .catch(async () => adminDb().collection(`users/${client.uid}/auditTrail`).limit(50).get());

    for (const doc of snap.docs) {
      const data = doc.data();
      const occurredAt =
        data.occurredAt?.toDate?.()?.toISOString?.() ||
        new Date(reportToMs(data.occurredAt)).toISOString();
      const d = new Date(occurredAt);
      if (!isInReportRange(d, from, to, allTime)) continue;
      rows.push({
        id: doc.id,
        module: "Account",
        eventType: String(data.type || "event"),
        description: String(data.description || data.action || ""),
        clientName: client.name || client.email || undefined,
        performedBy: data.performedByUid || undefined,
        occurredAt,
      });
    }
  }

  return rows.sort((a, b) => new Date(b.occurredAt).getTime() - new Date(a.occurredAt).getTime());
}

function filterInvoicesInRange(rows: AdminReportInvoiceRow[], from: Date, to: Date, allTime: boolean) {
  if (allTime) return rows;
  return rows.filter((row) => {
    const ms = reportToMs(row.createdAt) || reportToMs(row.date);
    return isInReportRange(new Date(ms), from, to, false);
  });
}

function buildDayBuckets(from: Date, to: Date) {
  const buckets = new Map<string, { label: string; revenue: number; shipped: number; received: number; requests: number }>();
  const days = Math.min(differenceInCalendarDays(to, from) + 1, 90);
  for (let i = 0; i < days; i++) {
    const d = new Date(from.getFullYear(), from.getMonth(), from.getDate() + i);
    if (d > to) break;
    const key = format(d, "yyyy-MM-dd");
    buckets.set(key, {
      label: format(d, "MMM d"),
      revenue: 0,
      shipped: 0,
      received: 0,
      requests: 0,
    });
  }
  return buckets;
}

function buildMonthBuckets(from: Date, to: Date) {
  const buckets = new Map<string, { label: string; revenue: number; shipped: number; received: number; requests: number }>();
  let cursor = startOfMonth(from);
  const end = endOfMonth(to);

  while (cursor <= end) {
    const key = format(cursor, "yyyy-MM");
    buckets.set(key, {
      label: format(cursor, "MMM yyyy"),
      revenue: 0,
      shipped: 0,
      received: 0,
      requests: 0,
    });
    cursor = subMonths(cursor, -1);
  }

  return buckets;
}

function bucketKeyForDate(dateMs: number, allTime: boolean): string {
  const d = new Date(dateMs);
  return allTime ? format(d, "yyyy-MM") : format(d, "yyyy-MM-dd");
}

export async function buildAdminReport(input: BuildAdminReportInput): Promise<AdminReportSummary> {
  const allTime = input.allTime ?? false;
  const from = reportStartOfDay(input.from);
  const to = reportEndOfDay(input.to);
  const users = await loadAllUsers();
  const { clientUsers, scopeLabel } = resolveClientScope(users, input.callerUid, input.clientId);
  const allowedIds = new Set(clientUsers.map((u) => u.uid!).filter(Boolean));
  const userNameById = new Map(clientUsers.map((u) => [u.uid!, u.name || u.email || u.uid!]));

  const [allInvoices, allCommissions] = await Promise.all([
    loadInvoicesForUsers([...allowedIds]),
    loadCommissions(),
  ]);

  const invoices = filterInvoicesInRange(allInvoices, from, to, allTime);
  const commissions = allCommissions.filter((c) => {
    if (!allowedIds.has(c.clientId)) return false;
    return isInReportRange(new Date(reportToMs(c.createdAt)), from, to, allTime);
  });

  const [shippedRows, inventoryRows, shipReqRows, invReqRows, returnRows, disposeRows, auditRows] =
    await Promise.all([
      loadCollectionGroupActivities("shipped", allowedIds, from, to, allTime, (path, data) => {
        const occurredMs = pickReportDateMs(data, ["date", "createdAt", "dispatchedAt"]);
        if (!occurredMs) return null;
        return {
          id: path,
          userId: uidFromFirestorePath(path),
          clientName: userNameById.get(uidFromFirestorePath(path)) || "",
          type: "Units Shipped",
          description: `Outbound shipment`,
          quantity: Number(data.shippedQty) || Number(data.totalUnits) || 0,
          status: "shipped",
          occurredAt: new Date(occurredMs).toISOString(),
        };
      }),
      loadCollectionGroupActivities("inventory", allowedIds, from, to, allTime, (path, data) => {
        const occurredMs = pickReportDateMs(data, ["receivingDate", "dateAdded", "approvedAt", "createdAt"]);
        if (!occurredMs) return null;
        return {
          id: path,
          userId: uidFromFirestorePath(path),
          clientName: userNameById.get(uidFromFirestorePath(path)) || "",
          type: "Inventory Received",
          description: String(data.productName || "Inventory item"),
          quantity: Number(data.quantity) || Number(data.receivedQuantity) || 0,
          status: String(data.status || ""),
          occurredAt: new Date(occurredMs).toISOString(),
        };
      }),
      loadCollectionGroupActivities("shipmentRequests", allowedIds, from, to, allTime, (path, data) => {
        const occurredMs = pickReportDateMs(data, ["requestedAt", "date", "confirmedAt", "createdAt"]);
        if (!occurredMs) return null;
        return {
          id: path,
          userId: uidFromFirestorePath(path),
          clientName: userNameById.get(uidFromFirestorePath(path)) || "",
          type: "Shipment Request",
          description: "Client shipment request",
          status: String(data.status || ""),
          occurredAt: new Date(occurredMs).toISOString(),
        };
      }),
      loadCollectionGroupActivities("inventoryRequests", allowedIds, from, to, allTime, (path, data) => {
        const occurredMs = pickReportDateMs(data, ["requestedAt", "addDate", "receivingDate", "approvedAt", "createdAt"]);
        if (!occurredMs) return null;
        return {
          id: path,
          userId: uidFromFirestorePath(path),
          clientName: userNameById.get(uidFromFirestorePath(path)) || "",
          type: "Inventory Request",
          description: "Client inventory request",
          status: String(data.status || ""),
          occurredAt: new Date(occurredMs).toISOString(),
        };
      }),
      loadCollectionGroupActivities("productReturns", allowedIds, from, to, allTime, (path, data) => {
        const occurredMs = pickReportDateMs(data, ["createdAt", "updatedAt", "approvedAt", "requestedAt"]);
        if (!occurredMs) return null;
        return {
          id: path,
          userId: uidFromFirestorePath(path),
          clientName: userNameById.get(uidFromFirestorePath(path)) || "",
          type: "Product Return",
          description: "Product return request",
          status: String(data.status || ""),
          occurredAt: new Date(occurredMs).toISOString(),
        };
      }),
      loadCollectionGroupActivities("disposeRequests", allowedIds, from, to, allTime, (path, data) => {
        const occurredMs = pickReportDateMs(data, ["requestedAt", "approvedAt", "createdAt"]);
        if (!occurredMs) return null;
        return {
          id: path,
          userId: uidFromFirestorePath(path),
          clientName: userNameById.get(uidFromFirestorePath(path)) || "",
          type: "Dispose Request",
          description: "Dispose inventory request",
          status: String(data.status || ""),
          occurredAt: new Date(occurredMs).toISOString(),
        };
      }),
      loadAuditRows(clientUsers, from, to, allTime),
    ]);

  const activities = [
    ...shippedRows,
    ...inventoryRows,
    ...shipReqRows,
    ...invReqRows,
    ...returnRows,
    ...disposeRows,
  ].sort((a, b) => new Date(b.occurredAt).getTime() - new Date(a.occurredAt).getTime());

  const totalBilled = invoices.reduce((s, i) => s + (i.grandTotal || 0), 0);
  const totalPaid = invoices
    .filter((i) => String(i.status || "").toLowerCase() === "paid")
    .reduce((s, i) => s + (i.grandTotal || 0), 0);
  const totalPending = invoices
    .filter((i) => String(i.status || "").toLowerCase() !== "paid")
    .reduce((s, i) => s + (i.grandTotal || 0), 0);
  const unitsShipped = shippedRows.reduce((s, r) => s + (r.quantity || 0), 0);
  const unitsReceived = inventoryRows.reduce((s, r) => s + (r.quantity || 0), 0);

  const periodDays = allTime ? 0 : differenceInCalendarDays(to, from) + 1;
  const priorTo = subDays(from, 1);
  const priorFrom = subDays(from, periodDays);
  const priorInvoices = allTime ? [] : filterInvoicesInRange(allInvoices, priorFrom, priorTo, false);
  const priorRevenue = priorInvoices.reduce((s, i) => s + (i.grandTotal || 0), 0);

  const chartFrom = allTime ? startOfMonth(subMonths(new Date(), 23)) : from;
  const chartTo = allTime ? reportEndOfDay(new Date()) : to;
  const buckets = allTime ? buildMonthBuckets(chartFrom, chartTo) : buildDayBuckets(from, to);

  for (const inv of invoices) {
    const ms = reportToMs(inv.createdAt) || reportToMs(inv.date);
    if (!ms) continue;
    const key = bucketKeyForDate(ms, allTime);
    const b = buckets.get(key);
    if (b) b.revenue += inv.grandTotal || 0;
  }
  for (const row of shippedRows) {
    const ms = reportToMs(row.occurredAt);
    if (!ms) continue;
    const key = bucketKeyForDate(ms, allTime);
    const b = buckets.get(key);
    if (b) b.shipped += row.quantity || 0;
  }
  for (const row of inventoryRows) {
    const ms = reportToMs(row.occurredAt);
    if (!ms) continue;
    const key = bucketKeyForDate(ms, allTime);
    const b = buckets.get(key);
    if (b) b.received += row.quantity || 0;
  }
  for (const row of [...shipReqRows, ...invReqRows, ...returnRows, ...disposeRows]) {
    const ms = reportToMs(row.occurredAt);
    if (!ms) continue;
    const key = bucketKeyForDate(ms, allTime);
    const b = buckets.get(key);
    if (b) b.requests += 1;
  }

  const revenueByClient = new Map<string, number>();
  for (const inv of invoices) {
    const label = inv.clientName || inv.clientEmail || inv.userId;
    revenueByClient.set(label, (revenueByClient.get(label) || 0) + (inv.grandTotal || 0));
  }

  const commissionPending = commissions.filter((c) => c.status === "pending").reduce((s, c) => s + c.commissionAmount, 0);
  const commissionPaid = commissions.filter((c) => c.status === "paid").reduce((s, c) => s + c.commissionAmount, 0);

  let referringAgent: AdminReportSummary["referringAgent"] = null;
  if (input.clientId && clientUsers.length === 1) {
    const client = clientUsers[0];
    if (client.referredByAgentId) {
      const agent = users.find((u) => u.uid === client.referredByAgentId);
      if (agent) {
        referringAgent = {
          agentId: agent.uid!,
          agentName: agent.name || agent.email || "Agent",
          referralCode: agent.referralCode,
        };
      }
    }
  }

  return {
    period: {
      from: from.toISOString(),
      to: to.toISOString(),
      label: allTime ? "All time" : `${format(from, "MMM d, yyyy")} – ${format(to, "MMM d, yyyy")}`,
      allTime,
    },
    scope: {
      clientId: input.clientId,
      clientName: input.clientId ? scopeLabel : undefined,
      allClients: !input.clientId,
    },
    financial: {
      invoiceCount: invoices.length,
      totalBilled,
      totalPaid,
      totalPending,
      discountTotal: 0,
      averageInvoice: invoices.length ? totalBilled / invoices.length : 0,
    },
    commission: {
      totalEarned: commissionPending + commissionPaid,
      totalPending: commissionPending,
      totalPaid: commissionPaid,
      agentCount: new Set(commissions.map((c) => c.agentId)).size,
      commissionCount: commissions.length,
    },
    clientActivity: {
      unitsShipped,
      unitsReceived,
      shipmentRequests: shipReqRows.length,
      inventoryRequests: invReqRows.length,
      returns: returnRows.length,
      disposeRequests: disposeRows.length,
      activeClients: new Set(
        [
          ...invoices.map((i) => i.userId),
          ...shippedRows.map((r) => r.userId),
          ...inventoryRows.map((r) => r.userId),
          ...shipReqRows.map((r) => r.userId),
          ...invReqRows.map((r) => r.userId),
          ...returnRows.map((r) => r.userId),
          ...disposeRows.map((r) => r.userId),
        ].filter(Boolean)
      ).size,
    },
    growth: {
      revenueChangePct: allTime ? null : pctChange(totalBilled, priorRevenue),
      shippedChangePct: null,
      invoiceCountChangePct: allTime ? null : pctChange(invoices.length, priorInvoices.length),
      priorRevenue,
      priorShipped: 0,
      priorInvoiceCount: priorInvoices.length,
    },
    charts: {
      revenueByDay: Array.from(buckets.values()).map((b) => ({ label: b.label, value: b.revenue })),
      activityByDay: Array.from(buckets.values()).map((b) => ({
        label: b.label,
        shipped: b.shipped,
        received: b.received,
        requests: b.requests,
      })),
      requestMix: [
        { type: "Shipments", count: shipReqRows.length },
        { type: "Inventory", count: invReqRows.length },
        { type: "Returns", count: returnRows.length },
        { type: "Dispose", count: disposeRows.length },
      ],
      topClientsByRevenue: Array.from(revenueByClient.entries())
        .map(([client, revenue]) => ({ client, revenue }))
        .sort((a, b) => b.revenue - a.revenue)
        .slice(0, 8),
    },
    rows: {
      invoices,
      commissions,
      activities,
      audit: auditRows,
    },
    referringAgent,
  };
}
