import type { AdminReportSummary, AdminReportType } from "@/lib/admin-reports-types";
import { csvEscape } from "@/lib/admin-reports-utils";

function toCsv(header: string[], rows: string[][]): string {
  return [header.map(csvEscape).join(","), ...rows.map((r) => r.map((c) => csvEscape(String(c))).join(","))].join("\r\n");
}

export function buildAdminReportCsv(summary: AdminReportSummary, reportType: AdminReportType): string {
  const meta = [
    ["Report Type", reportType],
    ["Period", summary.period.label],
    ["Scope", summary.scope.allClients ? "All clients" : summary.scope.clientName || summary.scope.clientId || ""],
    [],
  ];

  switch (reportType) {
    case "financial":
      return [
        ...meta.map((r) => r.join(",")),
        "",
        toCsv(
          ["Client", "Email", "Invoice #", "Date", "Status", "Subtotal", "Grand Total", "Auto Generated"],
          summary.rows.invoices.map((r) => [
            r.clientName,
            r.clientEmail,
            r.invoiceNumber,
            r.date,
            r.status,
            r.subtotal.toFixed(2),
            r.grandTotal.toFixed(2),
            r.autoGenerated ? "Yes" : "No",
          ])
        ),
      ].join("\r\n");

    case "commission":
      return [
        ...meta.map((r) => r.join(",")),
        "",
        toCsv(
          ["Agent", "Client", "Invoice #", "Invoice Amount", "Rate %", "Tier", "Commission", "Status", "Created", "Paid At"],
          summary.rows.commissions.map((r) => [
            r.agentName,
            r.clientName,
            r.invoiceNumber,
            r.invoiceAmount.toFixed(2),
            r.commissionRate?.toString() || "",
            r.tier || "",
            r.commissionAmount.toFixed(2),
            r.status,
            r.createdAt,
            r.paidAt || "",
          ])
        ),
      ].join("\r\n");

    case "client_activity":
      return [
        ...meta.map((r) => r.join(",")),
        "",
        toCsv(
          ["Client", "Activity Type", "Description", "Quantity", "Status", "Date"],
          summary.rows.activities.map((r) => [
            r.clientName,
            r.type,
            r.description,
            r.quantity?.toString() || "",
            r.status || "",
            r.occurredAt,
          ])
        ),
      ].join("\r\n");

    case "audit":
      return [
        ...meta.map((r) => r.join(",")),
        "",
        toCsv(
          ["Module", "Event", "Description", "Client", "Agent", "Performed By", "Date"],
          summary.rows.audit.map((r) => [
            r.module,
            r.eventType,
            r.description,
            r.clientName || "",
            r.agentName || "",
            r.performedBy || "",
            r.occurredAt,
          ])
        ),
      ].join("\r\n");

    case "operations":
      return [
        ...meta.map((r) => r.join(",")),
        "",
        "Metric,Count",
        `Shipment Requests,${summary.clientActivity.shipmentRequests}`,
        `Inventory Requests,${summary.clientActivity.inventoryRequests}`,
        `Returns,${summary.clientActivity.returns}`,
        `Dispose Requests,${summary.clientActivity.disposeRequests}`,
        `Units Shipped,${summary.clientActivity.unitsShipped}`,
        `Units Received,${summary.clientActivity.unitsReceived}`,
        "",
        toCsv(
          ["Client", "Activity Type", "Description", "Quantity", "Status", "Date"],
          summary.rows.activities.map((r) => [
            r.clientName,
            r.type,
            r.description,
            r.quantity?.toString() || "",
            r.status || "",
            r.occurredAt,
          ])
        ),
      ].join("\r\n");

    case "overview":
    default:
      return [
        ...meta.map((r) => r.join(",")),
        "",
        "Section,Metric,Value",
        `Financial,Total Billed,${summary.financial.totalBilled.toFixed(2)}`,
        `Financial,Total Paid,${summary.financial.totalPaid.toFixed(2)}`,
        `Financial,Total Pending,${summary.financial.totalPending.toFixed(2)}`,
        `Financial,Invoice Count,${summary.financial.invoiceCount}`,
        `Commission,Total Earned,${summary.commission.totalEarned.toFixed(2)}`,
        `Commission,Pending,${summary.commission.totalPending.toFixed(2)}`,
        `Commission,Paid,${summary.commission.totalPaid.toFixed(2)}`,
        `Activity,Units Shipped,${summary.clientActivity.unitsShipped}`,
        `Activity,Units Received,${summary.clientActivity.unitsReceived}`,
        `Activity,Active Clients,${summary.clientActivity.activeClients}`,
        "",
        "=== INVOICES ===",
        toCsv(
          ["Client", "Invoice #", "Date", "Status", "Grand Total"],
          summary.rows.invoices.map((r) => [r.clientName, r.invoiceNumber, r.date, r.status, r.grandTotal.toFixed(2)])
        ),
        "",
        "=== COMMISSIONS ===",
        toCsv(
          ["Agent", "Client", "Invoice #", "Commission", "Status"],
          summary.rows.commissions.map((r) => [
            r.agentName,
            r.clientName,
            r.invoiceNumber,
            r.commissionAmount.toFixed(2),
            r.status,
          ])
        ),
        "",
        "=== ACTIVITY ===",
        toCsv(
          ["Client", "Type", "Description", "Qty", "Date"],
          summary.rows.activities.map((r) => [
            r.clientName,
            r.type,
            r.description,
            r.quantity?.toString() || "",
            r.occurredAt,
          ])
        ),
        "",
        "=== AUDIT ===",
        toCsv(
          ["Module", "Event", "Description", "Date"],
          summary.rows.audit.map((r) => [r.module, r.eventType, r.description, r.occurredAt])
        ),
      ].join("\r\n");
  }
}
