export type AdminReportType =
  | "overview"
  | "financial"
  | "commission"
  | "client_activity"
  | "operations"
  | "audit";

export type AdminReportInvoiceRow = {
  id: string;
  userId: string;
  clientName: string;
  clientEmail: string;
  invoiceNumber: string;
  date: string;
  status: string;
  subtotal: number;
  grandTotal: number;
  autoGenerated?: boolean;
  createdAt: string;
};

export type AdminReportCommissionRow = {
  id: string;
  agentId: string;
  agentName: string;
  clientId: string;
  clientName: string;
  invoiceNumber: string;
  invoiceAmount: number;
  commissionAmount: number;
  commissionRate?: number;
  tier?: string;
  status: string;
  createdAt: string;
  paidAt?: string;
};

export type AdminReportActivityRow = {
  id: string;
  userId: string;
  clientName: string;
  type: string;
  description: string;
  quantity?: number;
  status?: string;
  occurredAt: string;
};

export type AdminReportAuditRow = {
  id: string;
  module: string;
  eventType: string;
  description: string;
  clientName?: string;
  agentName?: string;
  performedBy?: string;
  occurredAt: string;
};

export type AdminReportSummary = {
  period: { from: string; to: string; label: string; allTime: boolean };
  scope: { clientId?: string; clientName?: string; allClients: boolean };
  financial: {
    invoiceCount: number;
    totalBilled: number;
    totalPaid: number;
    totalPending: number;
    discountTotal: number;
    averageInvoice: number;
  };
  commission: {
    totalEarned: number;
    totalPending: number;
    totalPaid: number;
    agentCount: number;
    commissionCount: number;
  };
  clientActivity: {
    unitsShipped: number;
    unitsReceived: number;
    shipmentRequests: number;
    inventoryRequests: number;
    returns: number;
    disposeRequests: number;
    activeClients: number;
  };
  growth: {
    revenueChangePct: number | null;
    shippedChangePct: number | null;
    invoiceCountChangePct: number | null;
    priorRevenue: number;
    priorShipped: number;
    priorInvoiceCount: number;
  };
  charts: {
    revenueByDay: { label: string; value: number }[];
    activityByDay: { label: string; shipped: number; received: number; requests: number }[];
    requestMix: { type: string; count: number }[];
    topClientsByRevenue: { client: string; revenue: number }[];
  };
  rows: {
    invoices: AdminReportInvoiceRow[];
    commissions: AdminReportCommissionRow[];
    activities: AdminReportActivityRow[];
    audit: AdminReportAuditRow[];
  };
  /** When a single client is selected — their referring commission agent (admin UI only). */
  referringAgent?: {
    agentId: string;
    agentName: string;
    referralCode?: string;
  } | null;
};

export type AgentStatementSummary = {
  period: { from: string; to: string; label: string; allTime: boolean };
  agent: {
    id: string;
    name: string;
    email: string;
    referralCode?: string;
    tier: string;
    rate: number;
  };
  earnings: {
    totalEarned: number;
    totalPending: number;
    totalPaid: number;
    commissionCount: number;
    qualifiedRevenue: number;
  };
  clients: {
    totalReferred: number;
    activeInPeriod: number;
  };
  growth: {
    earningsChangePct: number | null;
    priorEarnings: number;
    revenueChangePct: number | null;
  };
  charts: {
    earningsByDay: { label: string; value: number }[];
    revenueByClient: { client: string; revenue: number }[];
  };
  rows: {
    commissions: AdminReportCommissionRow[];
    referredClients: { id: string; name: string; email: string; status?: string }[];
  };
};
