/** Middle segment of system-generated receive lots: `{sku}-receiving-{expiry}-{nnn}` */
export const RECEIVE_LOT_SEGMENT = "receiving";

const AUTO_LOT_PATTERN = new RegExp(
  `^.+-${RECEIVE_LOT_SEGMENT}-(\\d{8}|NOEXP)-\\d{3}$`,
  "i"
);

/** Safe SKU token for lot strings (alphanumeric + hyphens). */
export function sanitizeSkuForReceiveLot(sku: string): string {
  const trimmed = sku.trim();
  if (!trimmed) return "SKU";
  const cleaned = trimmed
    .replace(/\s+/g, "-")
    .replace(/[^a-zA-Z0-9-]/g, "")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
  return cleaned || "SKU";
}

/** Expiry segment: YYYYMMDD from ISO date, or NOEXP when missing. */
export function expirySegmentForReceiveLot(expiry?: string | null): string {
  const d = expiry?.trim().slice(0, 10);
  if (!d || !/^\d{4}-\d{2}-\d{2}$/.test(d)) return "NOEXP";
  return d.replace(/-/g, "");
}

/**
 * System lot: `{Sku}-receiving-{expiryYYYYMMDD|NOEXP}-{3-digit random}`.
 * Example: `ABC123-receiving-20261231-042`
 */
export function generateReceiveLot(sku: string, expiry?: string | null): string {
  const skuPart = sanitizeSkuForReceiveLot(sku);
  const expPart = expirySegmentForReceiveLot(expiry);
  const rnd = String(Math.floor(Math.random() * 1000)).padStart(3, "0");
  return `${skuPart}-${RECEIVE_LOT_SEGMENT}-${expPart}-${rnd}`;
}

export function isAutoGeneratedReceiveLot(lot: string): boolean {
  return AUTO_LOT_PATTERN.test(lot.trim());
}

/**
 * Use operator-entered lot when provided; otherwise generate from SKU + optional expiry.
 * No expiry (e.g. auto parts) → segment `NOEXP`: `SKU-receiving-NOEXP-042`
 */
export function resolveReceiveLot(input: {
  sku: string;
  expiry?: string | null;
  lot?: string | null;
}): string {
  const manual = input.lot?.trim();
  if (manual) return manual;
  return generateReceiveLot(input.sku, input.expiry);
}

export function describeReceiveLotPattern(): string {
  return `SKU-${RECEIVE_LOT_SEGMENT}-YYYYMMDD-### or SKU-${RECEIVE_LOT_SEGMENT}-NOEXP-###`;
}

export function describeReceiveLotHint(): string {
  return "Leave lot blank to auto-generate. No expiry (auto parts, etc.) uses NOEXP in the lot code.";
}
